title: BizTalk.Factory SDK
description: User's Guide
# https://assets.webiconspng.com/uploads/2017/09/Rockets-PNG-Image-42412.png
favicon: https://github.com/icraftsoftware/biztalk.factory.github.io/raw/master/assets/icons/favicon.png
icon: fas fa-rocket
hide_github: true
show_downloads: false
plugins:
  - jekyll-seo-tag
remote_theme: benc-uk/theme-msdark
